### ISSUE TITLE
Question: Recommended system requirements

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1390]
May I know the recommended system requirements to run datart for 10, 100 and 1000 concurrent users who can build vizs using predefined views? Is there a proper way to estimate this?

CPU, memory, storage, etc.

**Comment by scottsut** [comment]
When only using a `jdbc` source, datart is equivalent to a web server, and the requirements for computing and storage are small. When using a `file` or `http` source, because datart uses h2 database for aggregation, it is necessary to adjust the server specification according to the size of the file or http response content and the number of people using datart, which needs to be considered on a case-by-case basis.

**Comment by clementchong** [comment]
If we consider only a single jdbc source connection, what would be the recommendation?

**Comment by scottsut** [comment]
There is no recommendation, just treat it as a web server.

**Comment by clementchong** [comment]
ok. based on start script, the java heap size is set to 2gb. Is this good for production use as well?

For CPU, I would think 2 cores at minimum. 4 cores would be good start for production.
